---
- hosts: all
  tasks:

  - name: nginx installing
    apk:
      name: nginx
      state: present
      update_cache: yes

  - name: nginx config copying
    template:
        src: config/nginx.conf.j2
        dest: /etc/nginx/nginx.conf

  - name: Install openrc
    apk:
      name: openrc
      state: present
      update_cache: yes

  - name: dependencies installing
    pip:
      requirements: /app/requirements.txt

  - name: app running
    command: python3 /app/main.py