version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itemsdb
      POSTGRES_HOST_AUTH_METHOD: trust 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres


  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: itemsdb
      DB_USER: postgres
      DB_PASSWORD: password
    command: flask run --host=0.0.0.0 --port=8080
    depends_on:
      - db
    networks:
      - postgres

volumes:
  postgres_data:

networks:
  postgres: